server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
    url: jdbc:mysql://127.0.0.1:3306/book_manage?serverTimeZone=GMT%2b8&characterEncoding=utf-8 # %2b 就是 '+'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
    pool:
      # 最大连接
      max-active: 8
      # 最大空闲连接
      max-idle: 8
      # 最小空闲连接
      min-idle: 0
      # 连接等待时间
      max-wait: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有 mybatis 的 xml 文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印 SQL 语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

